/*
 * Created by SharpDevelop.
 * User: Mubarak - Date: 5/2/2015 - Time: 12:20 PM
 */
using System;

namespace waveletclient.app.Enum
{
	
	public class AppMessageEventEnum
	{
		public enum EnumEventType
		{
			// Company
			CREATE_COMPANY,
			UPDATE_COMPANY,
			DEACTIVATE_COMPANY,
			
			// Branch
			UPDATE_BRANCH,
			CREATE_BRANCH,
			DEACTIVATE_BRANCH,
			
			// Region
			UPDATE_REGION,
			CREATE_REGION,
			DEACTIVATE_REGION,
			
			// Profit Center
			UPDATE_PROFIT_CENTER,
			CREATE_PROFIT_CENTER,
			DEACTIVATE_PROFIT_CENTER,
			
			// Account Number
			UPDATE_ACCOUNT_NUMBER,
			CREATE_ACCOUNT_NUMBER,
			DEACTIVATE_ACCOUNT_NUMBER,
			
			// Account Number
			UPDATE_GLCODE,
			CREATE_GLCODE,
			DEACTIVATE_GLCODE,
			
			// Account Department
			UPDATE_ACCOUNT_DEPARTMENT,
			CREATE_ACCOUNT_DEPARTMENT,
			DEACTIVATE_ACCOUNT_DEPARTMENT,
			
			// Project
			UPDATE_PROJECT,
			CREATE_PROJECT,
			DEACTIVATE_PROJECT,
			
			// Postcode
			UPDATE_POSTCODE,
			CREATE_POSTCODE,
			DEACTIVATE_POSTCODE,
			
			// Journal Batch
			UPDATE_JOURNAL_BATCH,
			CREATE_JOURNAL_BATCH,
			CANCEL_JOURNAL_BATCH,
			VERIFY_JOURNAL_BATCH,
			LOCK_JOURNAL_BATCH,
			UNLOCK_JOURNAL_BATCH,
			POST_JOURNAL_BATCH,

			// Journal
			UPDATE_DOC_JOURNAL,
			CREATE_DOC_JOURNAL,
			CANCEL_DOC_JOURNAL,

			// [start] GST Module - Config
			
			// Tax Code
			CREATE_TAX_CODE,
			UPDATE_TAX_CODE,
			DEACTIVATE_TAX_CODE,
			
			// Tax Config
			UPDATE_TAX_CONFIG,
			
			// [end]
			
			// Business Division
			UPDATE_BUSINESS_DIVISION,
			CREATE_BUSINESS_DIVISION,
			DEACTIVATE_BUSINESS_DIVISION,
			
			// Store Division
			UPDATE_STORE_DIVISION,
			CREATE_STORE_DIVISION,
			DEACTIVATE_STORE_DIVISION,
			
			// Fiscal year
			UPDATE_FISCAL_YEAR,
			CREATE_FISCAL_YEAR,
			DEACTIVATE_FISCAL_YEAR,
			UPDATE_TAX_YEAR,
			CREATE_TAX_YEAR,

			// Filing Header
			UPDATE_FILING_HEADER,
			CREATE_FILING_HEADER,
			DEACTIVATE_FILING_HEADER,
			
			// GL Doc Type
			UPDATE_GL_DOC_TYPE,
			CREATE_GL_DOC_TYPE,
			DEACTIVATE_GL_DOC_TYPE,
			
			// Source
			UPDATE_SOURCE,
			CREATE_SOURCE,
			DEACTIVATE_SOURCE,
			
			// Inter Company
			UPDATE_INTER_COMPANY,
			CREATE_INTER_COMPANY,
			DEACTIVATE_INTER_COMPANY,
			
			// Daily Journal
			CLOSE_DAILY_JOURNAL,
			REOPEN_DAILY_JOURNAL,
			
			// Intercomp Journal
			CREATE_INTERCOMP_JOURNAL,
			CLOSE_INTERCOMP_JOURNAL,
			
			// Fiscal Period
			OPEN_FISCAL_PERIOD,
			REOPEN_FISCAL_PERIOD,
			CHANGE_FISCAL_PERIOD,
			CLOSE_FISCAL_PERIOD,		// Month End
			
			// Fiscal Year
			CLOSE_FINANCIAL_YEAR,		// Year End
			OPEN_FINANCIAL_YEAR,
			
			// Item Code
			CREATE_ITEM_CODE,
			UPDATE_ITEM_CODE,
			DEACTIVATE_ITEM_CODE,
			
			// Bank
			UPDATE_BANK,
			CREATE_BANK,
			DEACTIVATE_BANK,
			
			// Tax Group
			UPDATE_TAX_GROUP,
			CREATE_TAX_GROUP,
			DEACTIVATE_TAX_GROUP,
			
			// TaxFiling
			MY_GST_OUTPUT_TAX_FILING,
			MY_GST_OUTPUT_TAX_FILE_CUST_INV,
			MY_GST_INPUT_TAX_FILING,
			MY_GST_INPUT_TAX_UN_FILING,
			MY_GST_FILING_CYCLE,
			MY_GST_FILING_CYCLE_LOCK_NEW_REVISION,
			
			// Integration Project: Pass 1
			PS_INTEGRATION,
			APGL_INTEGRATION,
			APGL_INTEGRATION_LIST,
			TRIAL_BAL_GL_INTEGRATION,
			AP_INTEGRATION,
			AP_INTEGRATION_LIST,
			AP_BATCH_INTEGRATION,
			AR_INTEGRATION,
			
			// Integration Project: Pass 2
			AP_INTEGRATION_UPDATE,
			AP_INTEGRATION_UPDATE_LIST,
			AR_INTEGRATION_UPDATE,
			APGL_INTEGRATION_UPDATE,
			APGL_INTEGRATION_UPDATE_LIST,
			TRIAL_BAL_GL_INTEGRATION_POST,
			AP_INTEGRATION_POST,
			APGL_INTEGRATION_POST,
			PS_INTEGRATION_UPDATE,
			PS_INTEGRATION_POST,
			
			// Integration: Master Data
			ACCOUNT_DEPARTMENT_LIST_INTEGRATE,
			GLCODE_LIST_INTEGRATE,
			BRANCH_LIST_INTEGRATE,
			BUSINESS_DIVISION_LIST_INTEGRATE,
			STORE_DIVISION_LIST_INTEGRATE,
			COMPANY_LIST_INTEGRATE,
			PROFIT_CENTER_LIST_INTEGRATE,
			TAX_GROUP_LIST_INTEGRATE,
			
			//Users
			CREATE_USER,
			UPDATE_USER,
			RESET_USER_PASSWORD,
		}
	}
}
